### ISSUE TITLE
[Suggestion] Hide messages after some time

### ISSUE THREAD

**Issue by ArekPiekarz** [patriksletmo/Dota2Translator#1]
Currently, translated messages stay on the screen indefinitely, they are hidden only when a new message appears and there is no space left for it. Instead they should disappear after similar time as original messages in chat. Maybe add an option to customize that time.

**Comment by patriksletmo** [comment]
Implemented as of 98f6ac98b43d87156d6851f22595680c8a7bdfa4. The fade delay is greater than the normal message delay because the overlay can not be toggled using the enter key.
