### ISSUE TITLE
[Bug] Updater doesn't work - "Sleep" is not recognized

### ISSUE THREAD

**Issue by ArekPiekarz** [patriksletmo/Dota2Translator#10]
When I launch Dota 2 Translator, I get a message that there is an update available. I click "Yes" to download it, I can see a new dialog with a progress bar and description of downloading files. After it comes to 100%, a console window appears with a message "'Sleep' is not recognized as an internal or external command, operable program or batch file.", repeating without end. I have to manually force it to stop.

Also, I'm not sure if D2T is supposed to update itself if I already have the newest version.

Tested on an official binary version from 18th March 2013, Windows 7 x64.

**Comment by patriksletmo** [comment]
The command prompt which displays the error is used to update the Updater.exe, and it will loop until the updater executable has been closed. The sleep command is there to make sure the loop does not use up unnecessary cpu load, and has been replaced with a fully universal (works on every Windows version) hack in ed7f94e382786f2b6d38538a66d8653248f5414e.

If you want the update to be applied correctly you can either replace Updater.exe with tmp_Updater.exe, or modify the bat file and run it. If you choose to modify the bat file you have to replace the line
`Sleep 1`
with
`ping 127.0.0.1 -n > nul`

**Comment by ArekPiekarz** [comment]
I'm not sure how it's programmed, but can't you use some event loop, which doesn't use much CPU? Or a timer?

**Comment by patriksletmo** [comment]
The current implementation for updating the Updater.exe relies on executing a bat file which replaces the file as soon as the updater is done executing.

It works something like this:

-> Check if Updater.exe is running.
Running:
-> Wait 1 second.
-> Go back to checking if updater.exe is running.
Not running:
-> Replace the file.
-> Start the program.

The wait part does not consume any CPU and makes sure we don't check if the program was closed as many times we can in one second.
