### ISSUE TITLE
Teach us mortals how to do that

### ISSUE THREAD

**Issue by ravishi** [patriksletmo/Dota2Translator#11]
This translator thing is really neat.

I wish I knew how to do something _like_ that, but I know nothing about this directx hooking thing.

So, could you point me _anything_ about the subject? Like a little description of how to do it, any other example programs, etc? Of course I'll read your source code and try to learn from it, but there may be more information about the technique you used you could share with us mortals?

Thank you in advance.

**Comment by patriksletmo** [comment]
Thanks! This is however not an issue, but I should have replied much earlier. 
Take a look at this article and source code:
http://spazzarama.com/2011/03/14/c-screen-capture-and-overlays-for-direct3d-9-10-and-11-using-api-hooks/
https://github.com/spazzarama/Direct3DHook
