### ISSUE TITLE
Cross-Platform

### ISSUE THREAD

**Issue by Phylu** [patriksletmo/Dota2Translator#12]
Since Steam and Dota2 are available not only on windows, a cross platform version would be great. 

I would love to use this on my Linux machine.

**Comment by Gasparen** [comment]
I've started a port for Linux in Python, it's not even close to beeing as good as the original but it's a start
https://github.com/Gasparen/Dota2TranslatorLinux

**Comment by Phylu** [comment]
Nice.
I will test it, as soon as possible.

**Comment by jchayan** [comment]
It's pretty hard to do since this never seemed to be thinked to be cross-platform, seeing the tools they used to make it..

**Comment by rackom** [comment]
I would like to see that on mac :) anyway good job

**Comment by Awk34** [comment]
Would love to see cross-platform, but might take a lot more work considering most of this mod/whatever's code is probably win specific
