### ISSUE TITLE
Dota2ChatInterface has stopped working

### ISSUE THREAD

**Issue by DreadBoy** [patriksletmo/Dota2Translator#17]
I'm on Windows 8.1 and I installed this translator. Whenever I want to launch it, it crashes instantly and produces this error message: 

```
Dota2ChatInterface has stopped working. 
```

When I try to debug it with VS, this exception is reported:

```
An unhandled exception of type 'System.DllNotFoundException' occurred in Dota2ChatInterface.exe
Additional information: Unable to load DLL 'Dota2ChatDLL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Requested .dll is in the same folder as .exe and translator is installed in default folder.

**Comment by patriksletmo** [comment]
Did you install WinPcap? I'm quite sure the DllNotFoundException is thrown if the file can be found but a dependency is missing

**Comment by DreadBoy** [comment]
I uninstalled translator, downloaded WinPcap from [this website](http://www.winpcap.org/) and installed it. Then I tried reinstalling translator but it was aborted with message:

```
A newer version of WinPcap (internal version 4.1.0.2980) is already installed on this machine.
The installation will be aborted.
```

**Comment by DreadBoy** [comment]
Never mind, I clicked ok and it did abort the installation of something but certainly not of translator. Installation of translator succeeded and I can run it normally. Tomorrow I'll be able to test it in-game but I will close this issue since the problem was solved. Thank you. :+1:

**Comment by patriksletmo** [comment]
Glad it worked! Exactly, the abort only regards the bundled Winpcap installer. The translator installer continues to run
