### ISSUE TITLE
Crashes DOTA 2 if started during a game

### ISSUE THREAD

**Issue by icheyne** [patriksletmo/Dota2Translator#18]
1. Accept a match.
2. Wait for match to load.
3. Start the translator

DOTA 2 crashes and I have to reconnect.

**Comment by patriksletmo** [comment]
Does this happen every time the translator is started at this point? There are some occasional problems with Dota crashing when adding the overlay, but I pretty much found it to happen randomly. There might also be an increased probability of crashing when in-game instead of in the menu.

**Comment by icheyne** [comment]
Crashes every time once I am in game. :-\

On Mon, Mar 16, 2015 at 8:33 PM, Patrik Sletmo notifications@github.com
wrote:

> Does this happen every time the translator is started at this point? There
> are some occasional problems with Dota crashing when adding the overlay,
> but I pretty much found it to happen randomly. There might also be an
> increased probability of crashing when in-game instead of in the menu.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/patriksletmo/Dota2Translator/issues/18#issuecomment-81923388
> .

## 

_Iain Cheyne_
iain@cheyne.net
+44 7941 574338

**Comment by patriksletmo** [comment]
I'm not able to reproduce the problem, I did however only try it in a unofficial lobby (not matchmaking). Does the crash occur for you in those lobbies as well?

**Comment by icheyne** [comment]
I started a lobby game and the translator opened fine. It just seems to crash in matchmaking games. Maybe it's the anti-cheater checks?

**Comment by icheyne** [comment]
I retested this more in matchmaking games and you're right that it's unreliable. Sometimes it crashes and sometimes not. I'm not sure how to test this for you. Is there a log I can send you after a crash?

**Comment by patriksletmo** [comment]
The crash is related to some error occurring during the injection process. I have created a test build using the latest version of EasyHook (the library I'm using for injection), could you check if it works any better?

https://github.com/patriksletmo/Dota2Translator/releases/tag/2015-03-26

**Comment by icheyne** [comment]
Thanks so much for this. I'll try it out next game. I'm embarrassed to say that the bug has stopped happening for me. I have tried launching it during before games, during games and during game loads, but can't reproduce it now.

I'll try it with Mumble to see if I can reproduce, but I'll also try this new build.

The problem is that I'm restricted to 3 or maybe 4 tests maximum a night...

**Comment by icheyne** [comment]
I had one crash while using your new build, but otherwise it's stable. How do I generate error logs?

I was thinking that a better enhancement of the translator would be a translation table of DOTA terms. I've figured out who Pudge is in Russian, but a lot of the other DOTA words get scrambled by the translator. I don't mind maintaining a translation table and getting the community to generate it, but it might be a lot of work for you?

**Comment by patriksletmo** [comment]
I am a bit uncertain about the error logs, but I think there should be some sort of dump in the dota 2 root directory. I doubt that I'd be able to find anything of value there, but I can always try!

Regarding the enhancement I must check if Google Translate gives some sort of indication of the original word in a translated sentence, which would be required to add this feature. If it does, I will try to add it as soon as I have time :)

**Comment by icheyne** [comment]
Thanks for considering this. I understand that you finished this tool a year or so ago.

Maybe the tool could parse the text for Dota 2 vocabulary before submitting it to Google Translate and then cut the DOTA 2 words out and then reinsert them after the translation?

**Comment by patriksletmo** [comment]
Added a new issue for the Dota 2 vocabulary (#21) as I found a possible approach.
